// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package common

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func FabricGaugeMetric(name string, value float64) *Metrics {
	return &Metrics{
		ID:    name,
		MType: "gauge",
		Value: &value,
	}
}

func FabricCounterMetric(name string, delta int64) *Metrics {
	return &Metrics{
		ID:    name,
		MType: "counter",
		Delta: &delta,
	}
}

func TestMetrics_MarshalJSON(t *testing.T) {
	tests := []struct {
		name    string
		metric  *Metrics
		want    []byte
		wantErr bool
	}{
		{
			"Marshal gauge metric",
			FabricGaugeMetric("gauge0", 1.1),
			[]byte(`{"id":"gauge0","type":"gauge","value":1.1}`),
			false,
		},
		{
			"Marshal counter metric",
			FabricCounterMetric("counter0", 1),
			[]byte(`{"id":"counter0","type":"counter","delta":1}`),
			false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.metric.MarshalJSON()
			assert.NoError(t, err)
			t.Log(string(got))
			assert.Equal(t, tt.want, got)
		})
	}
}
